Role para Hardening SSH
DadosAbertosDeFeira/iac-role-basica pull request #3
Opened 2021-04-27 14:41 UTC by glenonmateus

2021-05-01 13:10 UTC, gomex requested changes

2021-05-01 13:10 UTC, gomex commented on vars/main.yml
> +Protocol: 2
Seria melhor colocar isso no default, né?

2021-05-04 01:56 UTC, glenonmateus commented
Passei as definições das variáveis para o defaults/main.yml

2021-05-08 17:15 UTC, gomex requested changes
O PR está massa, atualiza os EoL que ja da pra mergear ;)

2021-05-08 17:15 UTC, gomex commented on defaults/main.yml
> +Protocol: 2
Poderia colocar uma linha em branco no fim do arquivo?

2021-05-08 17:15 UTC, gomex commented on handlers/main.yml
> +    state: restarted
Poderia colocar uma linha em branco no fim do arquivo?

2021-05-08 17:15 UTC, gomex commented on tasks/main.yml
> +- import_tasks: ssh.yml
Poderia colocar uma linha em branco no fim do arquivo?

2021-05-08 17:15 UTC, gomex commented on tasks/ssh.yml
> +    - Reiniciar sshd
Poderia colocar uma linha em branco no fim do arquivo?

2021-05-08 17:15 UTC, gomex commented on templates/sshd_config
> +Protocol {{ Protocol }}
Poderia colocar uma linha em branco no fim do arquivo?

2021-05-08 17:16 UTC, gomex commented
Pra fechar a issue https://github.com/DadosAbertosDeFeira/iac/issues/49 ainda precisamos de:

- Precisamos de um CI aqui
- Preciso colocar que os membros do sudo não precisam de senha pra virar sudo
- Criar um test pra validar esse hardening no CI

2021-05-08 19:19 UTC, merged